CREATE VIEW MOMENTUM_INDICATOR_VIEW AS
WITH MOMENTUM AS (
    WITH LAGGED AS (
        SELECT "TIMESTAMP", "TICKER", "CLOSE", "VOLUME", 
        COALESCE(LAG("CLOSE", 1) OVER (ORDER BY "TICKER", "TIMESTAMP"), 0) AS "PREV_CLOSE",
        COALESCE(LAG("VOLUME", 1) OVER (ORDER BY "TICKER", "TIMESTAMP"), 0) AS "PREV_VOLUME" FROM QUOTE
    )
    SELECT 
        "TIMESTAMP",
        "TICKER", 
        ("CLOSE"-"PREV_CLOSE") / (ABS("PREV_CLOSE") + ABS("CLOSE")) * ("VOLUME"-"PREV_VOLUME") / (ABS("PREV_VOLUME") + ABS("VOLUME")) AS "MOMENTUM"
    FROM LAGGED
)
SELECT 
    "TIMESTAMP",
    "TICKER",
    "MOMENTUM" * POWER(10,ABS(CAST(LOG10(ABS("MOMENTUM")) AS INTEGER))-1) "NORMALIZED_MOMENTUM"
FROM MOMENTUM    
    