
DELETE FROM "QUOTE_FOREX";
ALTER TABLE "QUOTE_FOREX" ADD "MARKET_CAP_LOG10" DOUBLE PRECISION NOT NULL;
ALTER TABLE "QUOTE_FOREX" ADD "BETA_LOG" DOUBLE PRECISION NOT NULL;
DROP VIEW "QUOTE";
CREATE VIEW "QUOTE" AS
SELECT 
    "TICKER", "TIMESTAMP", 
    "OPEN"::DECIMAL(18,6), "HIGH"::DECIMAL(18,6), 
    "LOW"::DECIMAL(18,6), "CLOSE"::DECIMAL(18,6), 
    "VOLUME",
    "MARKET_CAP_LOG10",
    "BETA_LOG"
FROM "QUOTE_STOCKS"
UNION ALL
select
    "TICKER", "TIMESTAMP", 
    "OPEN", "HIGH", 
    "LOW", "CLOSE", 
    "VOLUME",
    "MARKET_CAP_LOG10",
    "BETA_LOG"
FROM "QUOTE_FOREX";
    