-- Active: 1761234047525@@nas@5432@qf
CREATE TABLE IF NOT EXISTS  QUOTE (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "OPEN" DECIMAL(10,2) NOT NULL,
    "HIGH" DECIMAL(10,2) NOT NULL,
    "LOW" DECIMAL(10,2) NOT NULL,
    "CLOSE" DECIMAL(10,2) NOT NULL,
    "VOLUME" BIGINT NOT NULL,
    CONSTRAINT QUOTE_PK PRIMARY KEY ("TIMESTAMP", "TICKER")
);
