CREATE TABLE IF NOT EXISTS  "QUOTE_STOCKS" (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "OPEN" DECIMAL(10,2) NOT NULL,
    "HIGH" DECIMAL(10,2) NOT NULL,
    "LOW" DECIMAL(10,2) NOT NULL,
    "CLOSE" DECIMAL(10,2) NOT NULL,
    "VOLUME" BIGINT NOT NULL,
    CONSTRAINT QUOTE_PK_STOCKS PRIMARY KEY ("TIMESTAMP", "TICKER")
);

-- Active: 1761234047525@@nas@5432@qf
CREATE TABLE IF NOT EXISTS  "QUOTE_FOREX" (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "OPEN" DECIMAL(18,6) NOT NULL,
    "HIGH" DECIMAL(18,6) NOT NULL,
    "LOW" DECIMAL(18,6) NOT NULL,
    "CLOSE" DECIMAL(18,6) NOT NULL,
    "VOLUME" BIGINT NOT NULL,
    CONSTRAINT QUOTE_PK_FOREX PRIMARY KEY ("TIMESTAMP", "TICKER")
);

        
CREATE VIEW "QUOTE" AS
SELECT 
    "TICKER", "TIMESTAMP", 
    "OPEN"::DECIMAL(18,6), "HIGH"::DECIMAL(18,6), 
    "LOW"::DECIMAL(18,6), "CLOSE"::DECIMAL(18,6), 
    "VOLUME"
FROM "QUOTE_STOCKS"
UNION ALL
select
    "TICKER", "TIMESTAMP", 
    "OPEN", "HIGH", 
    "LOW", "CLOSE", 
    "VOLUME"
FROM "QUOTE_FOREX";
