
CREATE TABLE IF NOT EXISTS INDICATOR_WAVELET (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "ϴ1" DOUBLE PRECISION NOT NULL,
    "ϴ2" DOUBLE PRECISION NOT NULL,
    "ϴ3" DOUBLE PRECISION NOT NULL,
    "ϴ4" DOUBLE PRECISION NOT NULL,
    "W" DOUBLE PRECISION NOT NULL,
    "Wd" DOUBLE PRECISION NOT NULL,    
    "Wdd" DOUBLE PRECISION NOT NULL,    
    CONSTRAINT INDICATOR_WAVELET_FK FOREIGN KEY ("TIMESTAMP", "TICKER") REFERENCES QUOTE ("TIMESTAMP", "TICKER")
);