DROP VIEW MOMENTUM_INDICATOR_VIEW;
CREATE VIEW MOMENTUM_INDICATOR_VIEW AS
WITH LAGGED AS (
    SELECT "TIMESTAMP", "TICKER", "CLOSE", "VOLUME", 
    COALESCE(LAG("CLOSE", 1) OVER (ORDER BY "TICKER", "TIMESTAMP"), 0) AS "PREV_CLOSE",
    COALESCE(LAG("VOLUME", 1) OVER (ORDER BY "TICKER", "TIMESTAMP"), 0) AS "PREV_VOLUME" FROM QUOTE
)
SELECT 
    "TIMESTAMP",
    "TICKER", 
    ("CLOSE"-"PREV_CLOSE") / (ABS("PREV_CLOSE") + ABS("CLOSE")) * POWER(("VOLUME"-"PREV_VOLUME") / (ABS("PREV_VOLUME") + ABS("VOLUME")),2) AS MOMENTUM" FROM LAGGED