CREATE TABLE IF NOT EXISTS INDICATOR_DIR_PROB (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "G" DOUBLE PRECISION NOT NULL,
    "Gd" DOUBLE PRECISION NOT NULL,
    "S" DOUBLE PRECISION NOT NULL,
    "P↑" DOUBLE PRECISION NOT NULL,
    "P↓" DOUBLE PRECISION NOT NULL,
    "P" DOUBLE PRECISION NOT NULL,    
    "Pd" DOUBLE PRECISION NOT NULL,    
    "Pdd" DOUBLE PRECISION NOT NULL,    
    CONSTRAINT INDICATOR_DIR_PROB_FK FOREIGN KEY ("TIMESTAMP", "TICKER") REFERENCES QUOTE ("TIMESTAMP", "TICKER")
);
