CREATE TABLE INDICATOR_NORMALIZED (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "NORMALIZED_CLOSE" DOUBLE PRECISION NOT NULL,
    "NORMALIZED_VOLUME" DOUBLE PRECISION NOT NULL,
    CONSTRAINT INDICATOR_NORMALIZED_FK FOREIGN KEY ("TIMESTAMP", "TICKER") REFERENCES QUOTE ("TIMESTAMP", "TICKER")
)