-- Active: 1761234047525@@nas@5432@qf
CREATE TABLE IF NOT EXISTS  QUOTE (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "OPEN" DOUBLE PRECISION NOT NULL,
    "HIGH" DOUBLE PRECISION NOT NULL,
    "LOW" DOUBLE PRECISION NOT NULL,
    "CLOSE" DOUBLE PRECISION NOT NULL,
    "VOLUME" DOUBLE PRECISION NOT NULL,
    CONSTRAINT QUOTE_PK PRIMARY KEY ("TIMESTAMP", "TICKER")
);
