
CREATE TABLE IF NOT EXISTS INDICATOR_SCRODINGER (
    "TIMESTAMP" TIMESTAMP NOT NULL,
    "TICKER" VARCHAR(20) NOT NULL,
    "λ" DOUBLE PRECISION NOT NULL,
    "E_Low" DOUBLE PRECISION NOT NULL,
    "E_High" DOUBLE PRECISION NOT NULL,
    "Ö" DOUBLE PRECISION NOT NULL,
    "Öd" DOUBLE PRECISION NOT NULL,
    "Ödd" DOUBLE PRECISION NOT NULL,    
    CONSTRAINT INDICATOR_SCRODINGER_FK FOREIGN KEY ("TIMESTAMP", "TICKER") REFERENCES QUOTE ("TIMESTAMP", "TICKER")
);