MAX_RISK_PER_TRADE = 0.02
TRANSACTION_COMMISSION = 0.02 

STRONG_BULLISH =  int(1)
STRONG_BEARISH  = int(-1)
STALL = int(0)
MEAN_REVERSION_LONG = int(2)
MEAN_REVERSION_SHORT = int(-2)
F_STD_K_FACTOR = 1.5
SIGNAL_LABELS = {
    STALL: "STALL",
    STRONG_BULLISH: "STRONG_BULLISH",
    STRONG_BEARISH: "STRONG_BEARISH",
    MEAN_REVERSION_LONG: "MEAN_REVERSION_LONG",
    MEAN_REVERSION_SHORT: "MEAN_REVERSION_SHORT"
}



MONDAY = 0
TUESDAY = 1
WEDNESDAY = 2
THURSDAY = 3
FRIDAY = 4
SATURDAY = 5
SUNDAY = 6

MIN_ENERGY = 0.001